spring.application.name=ap2
# 1. URL de Conexão (Aponta para o localhost, na porta 3306, e define o nome do banco)
spring.datasource.url=jdbc:mysql://localhost:3306/ap2?serverTimezone=UTC

# 2. Usuário e Senha do seu MySQL Workbench
spring.datasource.username=root
spring.datasource.password=admin

# 3. Driver de conexão do MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver